version: "3.1"
services:
    go-links:
        container_name: go
        image: go:0.0.1-alpha.2
        build:
            context: ./../
            args:
                - UNAME=${ENV_USER}
                - UID=${ENV_UID}
                - GID=${ENV_GID}
            dockerfile: docker/${DOCKERFILE}
        environment:
            - PORT=${PORT}
        ports:
            - ${PORT}:${PORT}
        volumes:
            - ./../:/usr/src/app
